[2025-09-20T09:26:48.628+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sql_to_elastic.dataCleaning manual__2025-09-20T09:26:44.082900+00:00 [queued]>
[2025-09-20T09:26:48.636+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sql_to_elastic.dataCleaning manual__2025-09-20T09:26:44.082900+00:00 [queued]>
[2025-09-20T09:26:48.636+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-09-20T09:26:48.636+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-09-20T09:26:48.636+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-09-20T09:26:48.648+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): dataCleaning> on 2025-09-20 09:26:44.082900+00:00
[2025-09-20T09:26:48.658+0000] {standard_task_runner.py:52} INFO - Started process 2372 to run task
[2025-09-20T09:26:48.663+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'sql_to_elastic', 'dataCleaning', 'manual__2025-09-20T09:26:44.082900+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpf7hpe6a1', '--error-file', '/tmp/tmp_xrmrv2q']
[2025-09-20T09:26:48.665+0000] {standard_task_runner.py:80} INFO - Job 157: Subtask dataCleaning
[2025-09-20T09:26:48.722+0000] {task_command.py:371} INFO - Running <TaskInstance: sql_to_elastic.dataCleaning manual__2025-09-20T09:26:44.082900+00:00 [running]> on host 564f5208acb9
[2025-09-20T09:26:48.783+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sql_to_elastic
AIRFLOW_CTX_TASK_ID=dataCleaning
AIRFLOW_CTX_EXECUTION_DATE=2025-09-20T09:26:44.082900+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-09-20T09:26:44.082900+00:00
[2025-09-20T09:26:48.816+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 34, in dataCleaning
    df.columns = df.columns.str.lower().str.strip()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/accessor.py", line 181, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/strings/accessor.py", line 168, in __init__
    self._inferred_dtype = self._validate(data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/strings/accessor.py", line 225, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!
[2025-09-20T09:26:48.828+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=sql_to_elastic, task_id=dataCleaning, execution_date=20250920T092644, start_date=20250920T092648, end_date=20250920T092648
[2025-09-20T09:26:48.835+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 157 for task dataCleaning (Can only use .str accessor with string values!; 2372)
[2025-09-20T09:26:48.844+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-09-20T09:26:48.887+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
