[2025-09-20T09:41:08.328+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sql_to_elastic.saveToElastic manual__2025-09-20T09:41:01.385048+00:00 [queued]>
[2025-09-20T09:41:08.337+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: sql_to_elastic.saveToElastic manual__2025-09-20T09:41:01.385048+00:00 [queued]>
[2025-09-20T09:41:08.337+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2025-09-20T09:41:08.338+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2025-09-20T09:41:08.338+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2025-09-20T09:41:08.355+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): saveToElastic> on 2025-09-20 09:41:01.385048+00:00
[2025-09-20T09:41:08.365+0000] {standard_task_runner.py:52} INFO - Started process 2822 to run task
[2025-09-20T09:41:08.370+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'sql_to_elastic', 'saveToElastic', 'manual__2025-09-20T09:41:01.385048+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp8gnlbmge', '--error-file', '/tmp/tmptsxcebqv']
[2025-09-20T09:41:08.372+0000] {standard_task_runner.py:80} INFO - Job 185: Subtask saveToElastic
[2025-09-20T09:41:08.438+0000] {task_command.py:371} INFO - Running <TaskInstance: sql_to_elastic.saveToElastic manual__2025-09-20T09:41:01.385048+00:00 [running]> on host 564f5208acb9
[2025-09-20T09:41:08.509+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sql_to_elastic
AIRFLOW_CTX_TASK_ID=saveToElastic
AIRFLOW_CTX_EXECUTION_DATE=2025-09-20T09:41:01.385048+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-09-20T09:41:01.385048+00:00
[2025-09-20T09:41:08.520+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 92, in saveToElastic
    kwargs['ti'].xcom_push(key='data', value=data + "3")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[2025-09-20T09:41:08.537+0000] {taskinstance.py:1412} INFO - Marking task as FAILED. dag_id=sql_to_elastic, task_id=saveToElastic, execution_date=20250920T094101, start_date=20250920T094108, end_date=20250920T094108
[2025-09-20T09:41:08.548+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 185 for task saveToElastic (unsupported operand type(s) for +: 'NoneType' and 'str'; 2822)
[2025-09-20T09:41:08.591+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2025-09-20T09:41:08.619+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
